# Generated by Django 5.1.7 on 2025-03-27 19:27

import ulid
from django.db import migrations, models

import ulid_django.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "etag",
                    ulid_django.models.ULIDField(
                        default=ulid.ULID,
                        blank=True,
                        null=True,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["etag"], name="example_ite_etag_a829b0_idx")
                ],
            },
        ),
    ]
